sudo: false
language: ruby
cache: bundler
rvm:
- 2.5.1

install:
  # Install Jekyll and dependencies
  - bundle install

script: bundle exec rake site:deploy --quiet #--trace

# Generate your secure token with the travis gem:
# get Github token from your Travis CI profile page
# gem install travis
# GH_TOKEN from https://github.com/settings/tokens
# travis encrypt 'GIT_NAME="haikyuu" GIT_EMAIL="als.abdellah@gmail.com" GH_TOKEN='
env:
  global:
    secure: "lH7nnzynhIh2OaD+yqNFA4PG1UMuIyqXmX4BbO0KpYzxUNxq5dJjso3MybAkFNWnl6S0JL8Jxus441ytBjRsfzd/ijuwHAqno8XpiP4KEdxsCcOdUMfUhq0AjUNboD+u42YM7kbYAnBl2FSyMUEAqahGuQRYufQnaXbC1G17e6yN8E1bv8irspSoTK1BSEIVCqfJ5rXcCLHN1uRgSoGIUJPLp5xRCxaTOYkeHZt1S23SEgaHsBfCFNIHBNuVKwIUety3OLZ6g+7HKSYkqUTG8rI59eEJAAW0tcMcybw11LBkVrC3KVN0Hqa1qHfpYLNeiDHqRi0dyL+clP4G67MPAopATheUAqI/v2h5f+okk3bqfAsEgCk3zJY6+yPIde/jfJE7h8mg1f/5+1Z1xe31SxER46TIB1sTcX79f085mhaoS+siTpFL488dEqcer60a9UJi7io8mvx7Zt8eKCh7wdnZn214r65v+24RimUGDubasyTqUZ+NQmLDDh4iVN68eGDfdeqbdLLYRBZBx/RjRbdm28uoAR2UZjYhxfa7JhcKql+TArek0t19sDln5AmH/Cy/avrSQfhSUROG3MDt9q7/QFscyiviv8DpCQdKrVdBc0jSkBpK2BnHviueCI48epgHc8jDcmEawKpILz+BSXygiBQ/G7hHfJnUQ+BZI0s="
branches:
  only:
    - master
